In [1]:
import torch
import torch.nn as nn
import torchvision
from torch.utils.data import DataLoader, Dataset
import numpy as np
import math

import matplotlib.pyplot as plt

In [2]:
class Wine_dataset(Dataset):
    
    def __init__(self):
        # data loading
        xy = np.loadtxt("data/wine.csv", delimiter=",", skiprows=1)
        self.x = torch.from_numpy(xy[:, 1:].astype(np.float32))
        self.y = torch.from_numpy(xy[:, 0].astype(np.float32))
        self.n_samples = xy.shape[0] 
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return self.n_samples

In [3]:
dataset = Wine_dataset()
first_data = dataset[0]
features, label = first_data


print(features)
print(label)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor(1.)


In [4]:
dataloader = DataLoader(dataset = dataset, batch_size = 4, shuffle = True)
dataiter = iter(dataloader)
batch = dataiter.next()

features, labels = batch
print(features.shape, labels.shape)

torch.Size([4, 13]) torch.Size([4])


In [5]:
num_epochs = 2
batch_size = 4
total_samples = len(dataset)
n_iter = math.ceil(total_samples / batch_size)
print(n_iter)

45


In [6]:
for epoch in range(num_epochs):
    for i, (features, label) in enumerate(dataloader):
        if (i+1)%5 == 0:
            print(f"epoch {epoch+1}/{num_epochs}, step = {i+1}/{n_iter}, inputs_shape = {features.shape}")

epoch 1/2, step = 5/45, inputs_shape = torch.Size([4, 13])
epoch 1/2, step = 10/45, inputs_shape = torch.Size([4, 13])
epoch 1/2, step = 15/45, inputs_shape = torch.Size([4, 13])
epoch 1/2, step = 20/45, inputs_shape = torch.Size([4, 13])
epoch 1/2, step = 25/45, inputs_shape = torch.Size([4, 13])
epoch 1/2, step = 30/45, inputs_shape = torch.Size([4, 13])
epoch 1/2, step = 35/45, inputs_shape = torch.Size([4, 13])
epoch 1/2, step = 40/45, inputs_shape = torch.Size([4, 13])
epoch 1/2, step = 45/45, inputs_shape = torch.Size([2, 13])
epoch 2/2, step = 5/45, inputs_shape = torch.Size([4, 13])
epoch 2/2, step = 10/45, inputs_shape = torch.Size([4, 13])
epoch 2/2, step = 15/45, inputs_shape = torch.Size([4, 13])
epoch 2/2, step = 20/45, inputs_shape = torch.Size([4, 13])
epoch 2/2, step = 25/45, inputs_shape = torch.Size([4, 13])
epoch 2/2, step = 30/45, inputs_shape = torch.Size([4, 13])
epoch 2/2, step = 35/45, inputs_shape = torch.Size([4, 13])
epoch 2/2, step = 40/45, inputs_shape = to

## Dataset Transforms

In [7]:
class Wine_dataset(Dataset):
    
    def __init__(self, transform = None):
        # data loading
        xy = np.loadtxt("data/wine.csv", delimiter=",", skiprows=1)
        self.x = torch.from_numpy(xy[:, 1:].astype(np.float32))
        self.y = torch.from_numpy(xy[:, 0].astype(np.float32))
        self.n_samples = xy.shape[0] 
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        
        if self.transform:
            sample = self.transform(sample)
        
        return sample
    
    def __len__(self):
        return self.n_samples

In [8]:
tarr = torch.tensor([1])
type(tarr) == torch.Tensor

True

In [9]:
type(torch.tensor([1]))

torch.Tensor

In [10]:
class ToTensor:
    def __call__(self, sample):
        inputs, labels = sample
        
        if type(inputs) == torch.Tensor:
            return inputs, labels
        return torch.from_numpy(inputs), torch.from_numpy(labels)

In [11]:
datatset = Wine_dataset(transform = ToTensor())
first_data = dataset[0]
features, label = first_data

print(features)
print(label)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor(1.)


In [12]:
class MylTransform:
    
    def __init__(self, factor):
        self.factor = factor
        
    def __call__(self, sample):
        features, labels = sample
        features *= self.factor
        
        return features, labels

In [13]:
composed = torchvision.transforms.Compose([MylTransform(2), ToTensor()])
dataset_1 = Wine_dataset(transform = composed)

In [14]:
first_data = dataset_1[0]
features, label = first_data

print(features)
print(label)

tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03])
tensor(1.)
